# Generated by Django 2.2.6 on 2019-11-28 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191117_0249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinfo',
            name='Card_Type',
        ),
    ]
