# Generated by Django 2.2.6 on 2019-11-29 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_paymentinfo_card_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinfo',
            name='Zip_code',
        ),
    ]
