# Generated by Django 2.2.6 on 2019-11-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_paymentinfo_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='Available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Shipping_Method',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
