# Generated by Django 2.2.6 on 2019-11-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20191130_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbook',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
